<?php
declare(strict_types=1);

/**
 * Textos UTF-8 canónicos para catálogos (fuente única para reparación de BD).
 * Coincide con los valores correctos de data_dictionary.php.
 */
return [
    'sedes' => [
        ['id' => 1, 'nombre' => 'Cúcuta'],
        ['id' => 2, 'nombre' => 'Ocaña'],
    ],
    'jornadas' => [
        ['id' => 1, 'nombre' => 'Diurna'],
        ['id' => 2, 'nombre' => 'Nocturna'],
        ['id' => 3, 'nombre' => 'Distancia'],
        ['id' => 4, 'nombre' => 'Virtual'],
    ],
    'tipos_identificacion' => [
        ['codigo' => 'CC', 'nombre' => 'Cédula de ciudadanía'],
        ['codigo' => 'TI', 'nombre' => 'Tarjeta de identidad'],
        ['codigo' => 'CE', 'nombre' => 'Cédula de extranjería'],
        ['codigo' => 'PPT', 'nombre' => 'Permiso por protección temporal'],
        ['codigo' => 'PAS', 'nombre' => 'Pasaporte'],
    ],
    'sexos' => [
        ['codigo' => 'M', 'nombre' => 'Masculino'],
        ['codigo' => 'F', 'nombre' => 'Femenino'],
        ['codigo' => 'O', 'nombre' => 'Otro / Prefiero no indicar'],
    ],
    'estados_solicitud' => [
        ['codigo' => 'pendiente', 'nombre' => 'Pendiente'],
        ['codigo' => 'en_revision', 'nombre' => 'En revisión'],
        ['codigo' => 'aprobada', 'nombre' => 'Aprobada'],
        ['codigo' => 'rechazada', 'nombre' => 'Rechazada'],
    ],
    'motivos_solicitud_estudiante' => [
        ['codigo' => 'salud', 'nombre' => 'Salud'],
        ['codigo' => 'economicos', 'nombre' => 'Económicos'],
        ['codigo' => 'cruce_horarios', 'nombre' => 'Cruce de horarios'],
        ['codigo' => 'cambio_residencia', 'nombre' => 'Cambio de residencia'],
        ['codigo' => 'otro', 'nombre' => 'Otro'],
    ],
    'prioridades_solicitud_docente' => [
        ['codigo' => 'baja', 'nombre' => 'Baja'],
        ['codigo' => 'media', 'nombre' => 'Media'],
        ['codigo' => 'alta', 'nombre' => 'Alta'],
    ],
    'categorias_docente' => [
        ['codigo' => 'auxiliar', 'nombre' => 'Auxiliar'],
        ['codigo' => 'asistente', 'nombre' => 'Asistente'],
        ['codigo' => 'asociado', 'nombre' => 'Asociado'],
        ['codigo' => 'titular', 'nombre' => 'Titular'],
    ],
    'tipos_contrato_docente' => [
        ['codigo' => 'tiempo_completo', 'nombre' => 'Tiempo completo'],
        ['codigo' => 'medio_tiempo', 'nombre' => 'Medio tiempo'],
        ['codigo' => 'catedra', 'nombre' => 'Cátedra'],
        ['codigo' => 'otro', 'nombre' => 'Otro'],
    ],
    'decisiones_resolucion_formal' => [
        ['codigo' => 'aprobado', 'nombre' => 'Aprobado — la solicitud sigue un curso favorable'],
        ['codigo' => 'rechazado', 'nombre' => 'Rechazado — no cumple requisitos'],
        ['codigo' => 'pendiente_informacion', 'nombre' => 'Pendiente de información (subsanación)'],
    ],
    'programas' => [
        ['id' => 117, 'codigo' => '90604', 'nombre' => 'Técnica Profesional en Operaciones Logísticas', 'id_sede' => 1],
        ['id' => 118, 'codigo' => '90605', 'nombre' => 'Tecnología en Gestión Logística Empresarial', 'id_sede' => 1],
        ['id' => 119, 'codigo' => '91390', 'nombre' => 'Técnica Profesional en Producción Gráfica', 'id_sede' => 1],
        ['id' => 120, 'codigo' => '107156', 'nombre' => 'Tecn. en Gestión de Contenidos Gráficos Publicitarios', 'id_sede' => 1],
        ['id' => 121, 'codigo' => '91388', 'nombre' => 'Diseño Gráfico', 'id_sede' => 1],
        ['id' => 123, 'codigo' => '107859', 'nombre' => 'Técnica Profesional en Soporte Informático', 'id_sede' => 1],
        ['id' => 124, 'codigo' => '107860', 'nombre' => 'Tecnología en Desarrollo de Software', 'id_sede' => 1],
        ['id' => 125, 'codigo' => '107861', 'nombre' => 'Ingeniería de Software', 'id_sede' => 1],
        ['id' => 126, 'codigo' => '107858', 'nombre' => 'Especialización en Gestión Pública', 'id_sede' => 1],
        ['id' => 127, 'codigo' => '108788', 'nombre' => 'Tecn. en Gestión de Contenidos Gráficos Public. Ocaña', 'id_sede' => 2],
        ['id' => 128, 'codigo' => '102041', 'nombre' => 'Diseño Gráfico Ocaña', 'id_sede' => 2],
        ['id' => 130, 'codigo' => '102517', 'nombre' => 'Tecn. en Gestión de Negocios Internacionales Ocaña', 'id_sede' => 2],
        ['id' => 131, 'codigo' => '102518', 'nombre' => 'Administración de Negocios Internacionales Ocaña', 'id_sede' => 2],
        ['id' => 133, 'codigo' => '102887', 'nombre' => 'Técnica Prof. en Operaciones Turísticas Virtual', 'id_sede' => 1],
        ['id' => 134, 'codigo' => '111410', 'nombre' => 'Tecnología en Gestión del Turismo Sostenible Virtual', 'id_sede' => 1],
        ['id' => 137, 'codigo' => '111412', 'nombre' => 'Tecnología en Gestión del Turismo Sostenible Presencial', 'id_sede' => 1],
        ['id' => 143, 'codigo' => '54348', 'nombre' => 'Técnica Profesional en Procesos Contables Presencial', 'id_sede' => 1],
        ['id' => 153, 'codigo' => '116880', 'nombre' => 'Administración de Negocios Internacionales Presencial', 'id_sede' => 1],
        ['id' => 159, 'codigo' => '104671', 'nombre' => 'Profesional en Diseño y Administración de Negocios de la Moda', 'id_sede' => 1],
        ['id' => 166, 'codigo' => '117775', 'nombre' => 'Especialización en Analítica de Datos para los Negocios Virtual', 'id_sede' => 1],
        ['id' => 176, 'codigo' => '91388', 'nombre' => 'Profesional en Diseño Gráfico', 'id_sede' => 1],
        ['id' => 177, 'codigo' => '118275', 'nombre' => 'Especialización en Marketing Digital Estratégico Presencial', 'id_sede' => 1],
    ],
    'tipos_solicitud_estudiante' => [
        ['id' => 1, 'codigo' => 'REQ_CANCEL_SEM', 'nombre' => 'Cancelación de semestre'],
        ['id' => 2, 'codigo' => 'REQ_CURSO_DIR', 'nombre' => 'Curso dirigido'],
        ['id' => 3, 'codigo' => 'REQ_CANCEL_ASIG', 'nombre' => 'Cancelación de asignaturas'],
        ['id' => 4, 'codigo' => 'REQ_CAMBIO_JORNADA', 'nombre' => 'Cambio de jornada'],
        ['id' => 5, 'codigo' => 'REQ_TRANSFER_INT', 'nombre' => 'Transferencia interna'],
        ['id' => 6, 'codigo' => 'REQ_EXAMEN_SUF', 'nombre' => 'Examen de validación por suficiencia'],
        ['id' => 7, 'codigo' => 'REQ_REINGRESO', 'nombre' => 'Reingreso'],
        ['id' => 8, 'codigo' => 'REQ_MATR_MIN', 'nombre' => 'Matrícula mínima de créditos'],
        ['id' => 9, 'codigo' => 'REQ_TRASLADO_SEDE', 'nombre' => 'Traslado de sede'],
        ['id' => 10, 'codigo' => 'REQ_PAGO_CRED', 'nombre' => 'Pago de créditos adicionales'],
        ['id' => 11, 'codigo' => 'REQ_CONST_EST', 'nombre' => 'Constancia de estudio'],
        ['id' => 12, 'codigo' => 'REQ_CERT_NOTAS', 'nombre' => 'Certificado de notas'],
        ['id' => 13, 'codigo' => 'REQ_OTRA', 'nombre' => 'Otra'],
    ],
    'tipos_solicitud_docente' => [
        ['id' => 1, 'codigo' => 'DOC_RECT_ACTA', 'nombre' => 'Rectificación de Acta de Calificaciones'],
        ['id' => 2, 'codigo' => 'DOC_PERM_LIC', 'nombre' => 'Permiso Remunerado / Licencia Corta'],
        ['id' => 3, 'codigo' => 'DOC_COM_EST', 'nombre' => 'Comisión de Estudios o Servicios'],
        ['id' => 4, 'codigo' => 'DOC_CERT_LAB', 'nombre' => 'Certificado Laboral y de Ingresos'],
        ['id' => 5, 'codigo' => 'DOC_MOD_CARGA', 'nombre' => 'Modificación de Carga Académica'],
        ['id' => 6, 'codigo' => 'DOC_DESC_INV', 'nombre' => 'Solicitud de Descarga por Investigación'],
        ['id' => 7, 'codigo' => 'DOC_RES_ESP', 'nombre' => 'Reserva de Espacios de Aprendizaje'],
        ['id' => 8, 'codigo' => 'DOC_MON_ASI', 'nombre' => 'Asignación de Monitor o Asistente'],
        ['id' => 9, 'codigo' => 'DOC_REPROG_EVAL', 'nombre' => 'Reprogramación de Evaluaciones'],
        ['id' => 10, 'codigo' => 'DOC_ANO_SAB', 'nombre' => 'Solicitud de Año Sabático'],
        ['id' => 11, 'codigo' => 'DOC_NOV_NOM', 'nombre' => 'Reporte de Novedades de Nómina'],
        ['id' => 12, 'codigo' => 'DOC_INS_EQUIP', 'nombre' => 'Solicitud de Insumos o Equipos'],
        ['id' => 13, 'codigo' => 'DOC_ASC_ESC', 'nombre' => 'Postulación a Ascenso en Escalafón'],
        ['id' => 14, 'codigo' => 'DOC_SAL_PED', 'nombre' => 'Solicitud de Salida Pedagógica'],
        ['id' => 15, 'codigo' => 'DOC_OTRA', 'nombre' => 'Otra / Petición General'],
    ],
];
